project:
  type: website

website:
  title: "Junze Tan's Website - Welcome!"
  navbar:
    left:
      - text: About Me Junze Tan
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



